schema_version = "1.0.0"

id = "shape_key_mirror_plus"
version = "1.8.0"
name = "Shape Key Mirror Plus"

maintainer = "Ciyorie(with GPT support)"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

description = """
Mirror shape key deltas across a selected axis, with support for multi-part symmetric meshes and split objects.
"""

tagline = "Mirror shape key deltas across symmetric axes"

tags = ["Mesh", "Modeling"]
